#!/bin/bash -x

export LD_LIBRARY_PATH=/fast_scratch/simianer/lfpe/nanomsg-0.5-beta/lib
export PYTHONPATH=~/.local/lib/python2.7/site-packages
./kill;./kill;rm /tmp/server.lock; ./server.rb ../example_pattr/conf.rb

