#!/bin/zsh -x

cd /fast_scratch/simianer/lfpe/lfpe/util
./kill; ./kill; ./kill;
for i in ../../sessions/product_de-en_beta_test_*; do
  echo $i
  echo $(basename $i)
  ./run_server $(basename $i) &; sleep 600;
done

