#!/bin/bash -x

export LD_LIBRARY_PATH=/fast_scratch/simianer/lfpe/lib/nanomsg-0.5-beta/lib:$LD_LIBRARY_PATH
export PYTHONPATH=/fast_scratch/simianer/lfpe/lib/python:$PYTHONPATH
export GEM_PATH=/fast_scratch/simianer/lfpe/lib/ruby/:$GEM_PATH
UTIL=/fast_scratch/simianer/lfpe/lfpe/util
SESSION=$1
DIR=/fast_scratch/simianer/lfpe/sessions/$SESSION

rm $DIR/work/lockfile
rm -r $DIR/work/
mkdir -p $DIR/work
cp $DIR/data.json.original $DIR/data.json
$UTIL/../server.rb $DIR/conf.rb &>$DIR/work/session.out

