#!/bin/zsh -x

#for i in `find ../sessions -maxdepth 1 | cut -d "/" -f 3 | grep -P "^sess_"`; do
for i in `cat ../sessions/sessions | cut -f 1`; do
  echo $i
  ./util/run_server $i &
  sleep 15
done

