#!/bin/bash -x

BASE_DIR=/srv/postedit
export LD_LIBRARY_PATH=$BASE_DIR/lib/nanomsg-0.5-beta/lib:$LD_LIBRARY_PATH
export PYTHONPATH=$BASE_DIR/lib/python:$PYTHONPATH
export GEM_PATH=$BASE_DIR/lib/ruby/:$GEM_PATH
UTIL=$BASE_DIR/lfpe/util
SESSION=$1
SESSION_DIR=$BASE_DIR/sessions/$SESSION

rm $SESSION_DIR/work/lockfile
rm -r $SESSION_DIR/work/
mkdir -p $SESSION_DIR/work
cp $SESSION_DIR/data.json.original $SESSION_DIR/data.json
cp $SESSION_DIR/g/original/* $SESSION_DIR/g/
$UTIL/../server.rb $SESSION_DIR/conf.rb &>$SESSION_DIR/work/session.out

