#!/bin/zsh -x

cd /srv/postedit/lfpe/util
./kill; ./kill; ./kill;
for i in `ls -1 ../../sessions/ | grep -v "_1_" | grep -v data | grep -v toy`; do
  echo $i
  echo $(basename $i)
  ./run_server $(basename $i) &; sleep 600;
done

