#!/bin/bash -x

export LD_LIBRARY_PATH=/fast_scratch/simianer/lfpe/nanomsg-0.5-beta/lib
export PYTHONPATH=/fast_scratch/simianer/lfpe/python
UTIL=/fast_scratch/simianer/lfpe/lfpe/util
SESSION=/fast_scratch/simianer/lfpe/sessions/tiny_test
clear;$UTIL/kill;$UTIL/kill;$UTIL/kill;rm $SESSION/work/lockfile; cp $SESSION/data.json.original $SESSION/data.json; $UTIL/../server.rb $SESSION/conf.rb

